### ISSUE TITLE
Mining aim bug

### ISSUE THREAD

**Issue by siltala1** [AdvancedCoding/MAZEGAME#1]
When mining gold, the player can look at another direction, and it will still be mining even though the pickaxe is pointing at the wrong direction. Joona's fault

**Comment by ossi1801** [comment]
Thank you for input on this issue. We are happy to announce that the bug has been fixed in commit: [b53a30a0917c7173b48ea4aed1928467e42b05ae](https://github.com/AdvancedCoding/MAZEGAME/commit/b53a30a0917c7173b48ea4aed1928467e42b05ae)

Best regards, 

Ossi
